### ISSUE TITLE
Parentheses inserted two times with the latest update

### ISSUE THREAD

**Issue by konart** [windwp/nvim-autopairs#71] opened 2021-06-27 08:57 UTC
Not sure if my config in at fault here but https://github.com/windwp/nvim-autopairs/commit/43020b163bcbea75151d31e29e02e5953317d34b introduced weird behavior for me (with the latest config example applied)

my autopairs config looks like this right now:
```
local remap = vim.api.nvim_set_keymap
local npairs = require('nvim-autopairs')
local Rule = require('nvim-autopairs.rule')

npairs.setup({
  ignored_next_char = "[%w%.]",
  check_ts = true,
  ts_config = {
      lua = {'string'},-- it will not add pair on that treesitter node
      javascript = {'string'}
  }
})

require('nvim-treesitter.configs').setup {
    autopairs = {enable = true}
}

local ts_conds = require('nvim-autopairs.ts-conds')

-- press % => %% is only inside comment or string
npairs.add_rules({
  Rule("%", "%", "lua")
    :with_pair(ts_conds.is_ts_node({'string','comment'})),
  Rule("$", "$", "lua")
    :with_pair(ts_conds.is_not_ts_node({'function'}))
})

require("nvim-autopairs.completion.compe").setup({
  map_cr = true, --  map <CR> on insert mode
  map_complete = true -- it will auto insert `(` after select function or method item
})
```

while compe's looks like this:
```
local remap = vim.api.nvim_set_keymap

vim.opt.completeopt = { "menuone" , "noselect" } -- "noinsert"

require('compe').setup {
  enabled = true;
  autocomplete = true;
  debug = false;
  min_length = 1;
  preselect = 'enable';
  throttle_time = 80;
  source_timeout = 200;
  incomplete_delay = 400;
  max_abbr_width = 100;
  max_kind_width = 100;
  max_menu_width = 100;
  documentation = true;

  source = {
    path = true;
    buffer = true;
    calc = true;
    nvim_lsp = true;
    nvim_lua = true;
    vsnip = true;
  };
}

local t = function(str)
  return vim.api.nvim_replace_termcodes(str, true, true, true)
end

local check_back_space = function()
    local col = vim.fn.col('.') - 1
    if col == 0 or vim.fn.getline('.'):sub(col, col):match('%s') then
        return true
    else
        return false
    end
end

-- Use (s-)tab to:
--- move to prev/next item in completion menuone
--- jump to prev/next snippet's placeholder
_G.tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t "<C-n>"
  elseif vim.fn.call("vsnip#available", {1}) == 1 then
    return t "<Plug>(vsnip-expand-or-jump)"
  elseif check_back_space() then
    return t "<Tab>"
  else
    return vim.fn['compe#complete']()
  end
end

_G.s_tab_complete = function()
  if vim.fn.pumvisible() == 1 then
    return t "<C-p>"
  elseif vim.fn.call("vsnip#jumpable", {-1}) == 1 then
    return t "<Plug>(vsnip-jump-prev)"
  else
    -- If <S-Tab> is not working in your terminal, change it to <C-h>
    return t "<S-Tab>"
  end
end

-- remap('i' , '<CR>','compe#confirm("<CR>")', {expr = true , noremap = true})

remap('i' , '<Tab>','v:lua.tab_complete()', {expr = true})
remap('s' , '<Tab>','v:lua.tab_complete()', {expr = true})
remap('i' , '<S-Tab>','v:lua.s_tab_complete()', {expr = true})
remap('s' , '<S-Tab>','v:lua.s_tab_complete()', {expr = true})
```

Now, after confirming a functon in compe's popup I have this kind of result:
```
foo((|))
```

In other words two pairs of parentheses are being inserted.

Did I understand the change incorrectly?

**Comment by windwp** [comment] 2021-06-27 10:57
what language do you use?
It will add a parentheses when item completion is method or function. 
i already test will lua,go and typescript.

require("nvim-autopairs.completion.compe").setup({
  map_cr = true, --  map <CR> on insert mode
  map_complete = false -- it will auto insert `(` after select function or method item
})

**Comment by konart** [comment] 2021-06-27 11:06
Only tested for Go for now.

setting `map_complete = false` does the trick as expected.

I think this have something to do with lsp config.

If I set `map_complete = true` but disable snippetSupport for LSP capabilities:

```
local capabilities = vim.lsp.protocol.make_client_capabilities()
capabilities.textDocument.completion.completionItem.snippetSupport = true
capabilities.textDocument.completion.completionItem.resolveSupport = {
  properties = {
    'documentation',
    'detail',
    'additionalTextEdits',
  }
}

lspconfig.gopls.setup{
    -- capabilities = capabilities,                   -- disabling for go 
}
```

everything works as expected too.

My guess is that both autopairs and compe (with  LSP snippet enabled) try to do the same thing.

**Comment by windwp** [comment] 2021-06-27 11:30
Hi I just update to check if it already have that round bracket then it will not add again.
So you can keep using that completionItem from lsp. It will add  on another lsp server doesn't have that feature.

**Comment by akinsho** [comment] 2021-06-28 11:35
I just hit this issue as well and was just about to ask if there is a way to exclude this setting for some languages. In my case when using `dartls` it has a feature called `completeFunctionCalls` which means that any time a `method` or `function` is used it will have and additional edit which adds in the parens and arguments. This is similar to how `sumneko_lua` offers `callSnippet="Replace"` in which case it will expand `myFunc` to `myFunc(args)`.

I don't think the logic to check if there is already a parens works maybe since I still get garbled input.
![compe-parens-bug](https://user-images.githubusercontent.com/22454918/123630203-27de8100-d80d-11eb-8c8a-d23fe06f6ae7.gif)
I think maybe autopairs is maybe not checking at the correct point in time after the lsp edit has already been done?

**Comment by windwp** [comment] 2021-06-29 02:16
@akinsho Can you check again.

**Comment by akinsho** [comment] 2021-06-29 07:17
@windwp that seems to be fixed now 👍🏾 thanks 💯

**Comment by konart** [comment] 2021-07-05 17:53
Works for me too. (sorry for the late reply. damn covid)

**Closed** 2021-07-06 01:24 UTC

**Comment by smjonas** [comment] 2022-01-05 13:28
I still have this problem when confirming a function suggestion from `sumneko_lua` with cmp. My config:
```lua
use({
  "windwp/nvim-autopairs",
  config = function()
    local cmp_autopairs = require("nvim-autopairs.completion.cmp")
    require("nvim-autopairs").setup({
      disable_filetype = { "TelescopePrompt", "vim", "tex" },
      -- Insert brackets after selecting function from cmp
      require("cmp").event:on(
        "confirm_done",
        cmp_autopairs.on_confirm_done({
          map_char = { tex = "" },
        })
      ),
    })
  end,
  after = "nvim-cmp",
})
```
It does not happen when I delete the `require("cmp").event:on(...)` part but then no brackets are inserted at all which I don't want.

### To reproduce
Type `vim.filetype.` in a lua file (sumneko-lua must be installed). Cmp shows `add` as a suggested function.

### Expected Behaviour
When confirming the selection `vim.filetype.add(|)` should be inserted (where `|` is the cursor position)


### Actual behaviour
`vim.filetype.add((|))` is inserted
